### ISSUE TITLE
[bug] output of pgbench breaks parser

### ISSUE THREAD

**Issue by thomasboni** [wilfriedroset/pgbencher#1]
Hello,

I encounter a parsing error when running the playbook. It's during èrun pgbench` task, the parser script fails.

It browse all lines, split each on `:` (or `=`) and try to cast values with 2 functions: `digit` and `with_unit`. If the line parsed end with the character `:` the list produced will be like `['text before colon', '']`. In this case, test `if not s[0].isdigit():` in function `with_unit` produce an `IndexError` which isn't catched.

Extract of my `pgbench` output :

```
transaction type: <builtin: TPC-B (sort of)>
scaling factor: 1
query mode: simple
number of clients: 2
number of threads: 2
number of transactions per client: 10
number of transactions actually processed: 20/20
latency average = 267.450 ms
tps = 7.478027 (including connections establishing)
tps = 8.141689 (excluding connections establishing)
statement latencies in milliseconds:                            ### Issue on this line
         0.003  \set aid random(1, 100000 * :scale)
         0.001  \set bid random(1, 1 * :scale)
         0.000  \set tid random(1, 10 * :scale)
         0.000  \set delta random(-5000, 5000)
        28.867  BEGIN;
        28.921  UPDATE pgbench_accounts SET abalance = abalance + :delta WHERE aid = :aid;
        28.987  SELECT abalance FROM pgbench_accounts WHERE aid = :aid;
        29.946  UPDATE pgbench_tellers SET tbalance = tbalance + :delta WHERE tid = :tid;
        49.663  UPDATE pgbench_branches SET bbalance = bbalance + :delta WHERE bid = :bid;
        43.454  INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (:tid, :bid, :aid, :delta, CURRENT_TIMESTAMP);
        32.852  END;
[...]
```

Error:
```
[thomas:~/workspace/tools/pgbencher] master(+4/-1)* 1 ± cat /tmp/pgbencher_out | python files/pgbench-parser.py
Traceback (most recent call last):                        
  File "files/pgbench-parser.py", line 127, in <module>                                                                
    main()                                                                                                             
  File "files/pgbench-parser.py", line 115, in main                                                                    
    value = cast(value)                        
  File "files/pgbench-parser.py", line 61, in with_unit                                                                
    if not s[0].isdigit():    
IndexError: string index out of range  
```

`pgbench` version:
```
[thomas:~] $ pgbench --version
pgbench (PostgreSQL) 11.4
```

Is this version of pgbench incompatible with this playbook ? How is the output in the version that you use ? 

I suppose that the playbook was written with a different version of pgbench which produce a different output. I will make a PR but I want to ensure that I will not break compatibility with other versions of pgbench.

**Comment by wilfriedroset** [comment]
You are absolutely correct. The output of pgbench change somewhere between 9.6 and 11.4+.
Here is an example with pgbench 9.6.15
```
transaction type: <builtin: TPC-B (sort of)>
scaling factor: 1
query mode: simple
number of clients: 10
number of threads: 2
number of transactions per client: 100
number of transactions actually processed: 1000/1000
latency average = 13.787 ms
tps = 725.332529 (including connections establishing)
tps = 727.040497 (excluding connections establishing)
script statistics:
 - statement latencies in milliseconds:
         0.009  \set aid random(1, 100000 * :scale)
         0.007  \set bid random(1, 1 * :scale)
         0.009  \set tid random(1, 10 * :scale)
         0.009  \set delta random(-5000, 5000)
         0.280  BEGIN;
         0.354  UPDATE pgbench_accounts SET abalance = abalance + :delta WHERE aid = :aid;
         0.347  SELECT abalance FROM pgbench_accounts WHERE aid = :aid;
         4.511  UPDATE pgbench_tellers SET tbalance = tbalance + :delta WHERE tid = :tid;
         5.076  UPDATE pgbench_branches SET bbalance = bbalance + :delta WHERE bid = :bid;
         0.278  INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (:tid, :bid, :aid, :delta, CURRENT_TIMESTAMP);
         0.893  END;
```

And now an example with pgbench 11.5
```
transaction type: <builtin: TPC-B (sort of)>
scaling factor: 1
query mode: simple
number of clients: 10
number of threads: 2
number of transactions per client: 100
number of transactions actually processed: 1000/1000
latency average = 11.755 ms
tps = 850.685691 (including connections establishing)
tps = 853.430826 (excluding connections establishing)
statement latencies in milliseconds:
         0.010  \set aid random(1, 100000 * :scale)
         0.008  \set bid random(1, 1 * :scale)
         0.008  \set tid random(1, 10 * :scale)
         0.007  \set delta random(-5000, 5000)
         0.260  BEGIN;
         0.361  UPDATE pgbench_accounts SET abalance = abalance + :delta WHERE aid = :aid;
         0.407  SELECT abalance FROM pgbench_accounts WHERE aid = :aid;
         3.938  UPDATE pgbench_tellers SET tbalance = tbalance + :delta WHERE tid = :tid;
         4.912  UPDATE pgbench_branches SET bbalance = bbalance + :delta WHERE bid = :bid;
         0.212  INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (:tid, :bid, :aid, :delta, CURRENT_TIMESTAMP);
         0.822  END;
```

As you can see the line `script statistics:` in 9.6 version disappear. I was using this line to stop the parsing.

I've update `pgbench-parser.py` to take into account both the old and the new output.
```
master(+36/-5) ± cat tests/samples/pgbench_9.6.15 | files/pgbench-parser.py
{"scaling factor": 1, "query mode": "simple", "number of clients": 10, "number of threads": 2, "number of transactions per client": 100, "number of transactions actually processed": 100.0, "latency average": {"value": 13.787, "unit": "ms"}, "tps (including connections establishing)": 725.332529, "tps (excluding connections establishing)": 727.040497}
master(+36/-5) ± cat tests/samples/pgbench_11.5 | files/pgbench-parser.py
{"scaling factor": 1, "query mode": "simple", "number of clients": 10, "number of threads": 2, "number of transactions per client": 100, "number of transactions actually processed": 100.0, "latency average": {"value": 11.755, "unit": "ms"}, "tps (including connections establishing)": 850.685691, "tps (excluding connections establishing)": 853.430826}
```
